### ISSUE TITLE
Prettier config conflict

### ISSUE THREAD

**Issue by roramigator** [oneleif/bfjWebsite-React#3]
![image](https://user-images.githubusercontent.com/55143159/105752141-e7ed3800-5f14-11eb-93d6-baea2b579266.png)

![image](https://user-images.githubusercontent.com/55143159/105752107-e02d9380-5f14-11eb-8cdb-2deadeff7763.png)

The configuration files are causing conflicts on build

**Comment by atmdboss** [comment]
The fix worked right? We can close this?
